"""update_organization_regnr_field

Revision ID: 379eb7fad554
Revises: 
Create Date: 2024-11-04 09:06:15.510927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379eb7fad554'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'expense_category', ['category_id'], ['id'])

    with op.batch_alter_table('expense_category', schema=None) as batch_op:
        batch_op.drop_constraint('expense_category_name_key', type_='unique')
        batch_op.create_unique_constraint('_name_uc', ['name'])

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regnr', sa.String(length=9)))
        batch_op.create_unique_constraint(None, ['regnr'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('regnr')

    with op.batch_alter_table('expense_category', schema=None) as batch_op:
        batch_op.drop_constraint('_name_uc', type_='unique')
        batch_op.create_unique_constraint('expense_category_name_key', ['name'])

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
