"""Add kwh column to Expense model

Revision ID: 46599494ecce
Revises: 943df735f8c8
Create Date: 2024-10-31 09:57:44.936587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46599494ecce'
down_revision = '943df735f8c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kwh', sa.Float(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('kwh')

    # ### end Alembic commands ###
