"""Add reimbursement status to trips

Revision ID: 4b9e5d985903
Revises: 3d2ce2907e96
Create Date: 2024-11-09 12:25:13.671494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b9e5d985903'
down_revision = '3d2ce2907e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reimbursement_status', sa.Enum('NOT_REQUESTED', 'PENDING', 'REIMBURSED', name='reimbursementstatus'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('reimbursement_status')

    # ### end Alembic commands ###
