"""add fuel expense fields

Revision ID: cc87c2cbc623
Revises: cdc1e788b1fc
Create Date: 2024-10-29 15:08:56.027646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc87c2cbc623'
down_revision = 'cdc1e788b1fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kilometers', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fuel_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('fuel_amount_liters', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('co2_emissions', sa.Float(), nullable=True))

    with op.batch_alter_table('expense_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_fuel', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('expense_category', schema=None) as batch_op:
        batch_op.drop_column('is_fuel')

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('co2_emissions')
        batch_op.drop_column('fuel_amount_liters')
        batch_op.drop_column('fuel_type')
        batch_op.drop_column('kilometers')

    # ### end Alembic commands ###
