"""Add receipt

Revision ID: ec58318e7a85
Revises: 2e4723a83b39
Create Date: 2024-11-05 21:27:24.178808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec58318e7a85'
down_revision = '2e4723a83b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('receipt_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('receipt_uploaded_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'expense_category', ['category_id'], ['id'])

    with op.batch_alter_table('expense_category', schema=None) as batch_op:
        batch_op.drop_constraint('expense_category_name_key', type_='unique')
        batch_op.create_unique_constraint('_name_uc', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_category', schema=None) as batch_op:
        batch_op.drop_constraint('_name_uc', type_='unique')
        batch_op.create_unique_constraint('expense_category_name_key', ['name'])

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('receipt_uploaded_at')
        batch_op.drop_column('receipt_path')
        batch_op.drop_column('receipt_filename')

    # ### end Alembic commands ###
